/**
 * Centralized error codes for server actions
 */
export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  ENCOUNTER_ALREADY_IN_PROGRESS: "ENCOUNTER_ALREADY_IN_PROGRESS",
  DUPLICATE_ENCOUNTER: "DUPLICATE_ENCOUNTER",
  ALREADY_CLAIMED: "ALREADY_CLAIMED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  SESSION_ERROR: "SESSION_ERROR",
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
